### ISSUE TITLE
sync state should also filter note's via recipient

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#104]
This was raised by @Dominik1999 , it is interesting to support state sync were the user can define the note it is interested on by the recipient field. This is useful for atomic swaps.

**Comment by bobbinth** [comment]
Is this to be able to retrieve a set of notes intended for atomic swaps? If so, this could be tricky because `recipient` includes `serial_num` and thus would be unique for each note.

The way I was thinking about handling this was through tags. Basically, we'd have different types of tags for different use cases.

We can define the exact schema later. For simplicity, let's say we have only 2 types of notes:
1. Notes sent to a specific account.
2. Notes for atomic swaps.

We can encode this info in a tag using the most significant bit - e.g.:
- If the most significant bit is $0$, this note is for a specific account and then the following bits contain an account ID of the recipient (or a portion thereof).
- If the most significant bit is $1$, this note is intended for an atomic swap, and the following bits encode some additional info about the swap (e.g., asset pair).

This way, the user can specify a tag for say "atomic swap notes which want to trade MATIC for ETH".

The above is just an example and we'd need to come up with a scheme that handles tag types more flexibly as over time people will come up with more use cases. Also, we may need to make some adjustments to how filtering by tags works during state sync as 16 bits provides little room for encoding extra info.

Lastly, one thing to note: there is a potential spamming vector here: someone could create a bunch of notes where a tag does not match the content (this is also true for our current use of tags). There could be various ways to deal with this (e.g., for standardized use cases nodes could detect this in public notes and not propagate them through the network) but this is something we'll need to think through.

**Comment by phklive** [comment]
As a newcomer to this project, I'd like to share my perspective on the discussion about tags.

I agree with @bobbinth's point that as our user base expands, we'll encounter a very diverse range of use cases, most that we did not envision. Given this, I believe it's not practical to establish specific tag types for p2id (pay to id) and aswap (atomic swap). My reasoning in the future is the following.

1. If we create specific tags only for p2id and aswap, it limits the scope and adaptability of our tagging system.

2. Alternatively, if we decide to assign new tag types for new scripts developed by us or our users, it could lead to an over-complicated system and high amounts of monitoring / politics.

This approach also risks compromising the principle of credible neutrality, similar to the issue faced by Ethereum core developers with pre-compiled contracts (picking winners) by choosing which script have tags and become "standard" and which do not.

I believe that giving freedom to users by giving them access to a user defined `tag` field could be the right solution.

**Comment by bobbinth** [comment]
A few things to clarify:

Tags are used exclusively for note discovery. As such, the protocol does not force users to use specific tags - so, users can now (and will in the future) be able to specify arbitrary tags for notes.

But we do need to set some standards (which users are free to follow or not), otherwise, note discovery would be too complicated and the UX would suffer. So, there are two things I think we should do:

1. Define high-level tag categories (these could be just a handful - for very high-level categorization).
2. For standardized scripts, define tag format.

For `P2ID` and `P2IDR` we already use a kind of a format. Specifically, a tag is set to the target account ID (we should probably change this to take only the first 32 bits of the account ID - or something like that).

For `ASWAP`, we don't have anything yet - but we also shouldn't use something that conflicts with `P2ID`/`P2IDR`. This is probably a separate discussion though (i'll try to write up some thoughts in `miden-base` on this later this week). For now, I think we can use zero for `ASWAP` tag.

**Comment by bobbinth** [comment]
Closing this as we'll try to handle all note routing via tag schemas described in https://github.com/0xPolygonMiden/miden-base/issues/402.
