### ISSUE TITLE
Verify transaction proofs

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#106]
ref: https://discord.com/channels/893151281848406016/1184427810736058420/1184532717564608602

**Comment by bobbinth** [comment]
There are two potential places to verify transaction proofs:

1. In the block producer as a part of [verify_tx()](https://github.com/0xPolygonMiden/miden-node/blob/main/block-producer/src/state_view/mod.rs#L46).
2. In the RPC as a part of [submit_prove_transaction()](https://github.com/0xPolygonMiden/miden-node/blob/main/rpc/src/server/api.rs#L82) handler. 

I think we definitely should do this in the RPC. This will require deserializing transaction and checking the proof, but it will also prevent transactions with invalid proofs getting to the block producer. This is desirable because RPC component is much easier to scale (i.e., by running on multiple instances with a load balancer).

It may also be good to re-verify transactions in the block producer - just in case (the proofs will be verified as a part of the batching process, but it may be good to do it via `verify_tx()` as well). If we do this, I think we should have a configuration option for the block producer - something like `check_tx_proofs`.

**Comment by bobbinth** [comment]
Closed by #220.
