### ISSUE TITLE
Remove additional CLI parameters

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#124]
CLI's of node components currently take a path to the config file and some additional parameters (e.g., `host`, `port`, `sqlite` for the store component). As far as I can tell, everything except for the config file, is currently ignored. So, we should remove these extra parameters as options.

**Comment by bobbinth** [comment]
The other option is to make them work - see https://github.com/0xPolygonMiden/miden-node/issues/75. But I'm not sure we need this.

**Comment by hackaugusto** [comment]
Without env variables and CLI options, it means that during deploying a configuration file needs to be generated, which adds a lot of complexity for smaller environments. Because not only you have to generate the files, you also have to manage them (as in, version, and location), and place them on correct location. env variables and cli allows one to deploy these systems without the extra overhead

**Comment by bobbinth** [comment]
I think we still need to understand how we want the deployment process to work in the longer term. For example:

- Do we go with separate binaries for each component (as we do now) or do we have a single binary and turn different components on/off via config params (as is described in [#92](https://github.com/0xPolygonMiden/miden-node/issues/92)?
- Do we expect people to compile from source or use docker images or something else?

For now, I think it is simpler to remove CLI options (as they literally don't do anything), and once we have a better picture of how things will work, we can re-introduce what makes sense.
