### ISSUE TITLE
TxQueue tests are flaky

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#125]
`test_build_batch_success` seems to fail sometimes in CI. The assert that triggers the failure is [here](https://github.com/0xPolygonMiden/miden-node/blob/59984a5d4969053c55edf148c978a30b0ada23e9/block-producer/src/txqueue/tests/mod.rs#L109) (i.e., a batch with no transactions is sent to the batch builder).

**Comment by plafer** [comment]
This test is really dependent on proper timing of things (e.g. I expect that after X ms I will only have sent 1 batch, etc etc). There's probably a better way to write it. This *might* involve rewriting the [interval tick logic](https://github.com/0xPolygonMiden/miden-node/blob/59984a5d4969053c55edf148c978a30b0ada23e9/block-producer/src/txqueue/mod.rs#L107) so that tests can control when ticks happen, independent of timing.

**Comment by hackaugusto** [comment]
IMO we should split the driver and the code. This is not always possible, but here it seems simple enough to have the `run` loops moved all the way to the top server. The unit tests should never have to spawn threads or have synchronization to work correctly (as in latches or sleeps). We should also have some way of moving time forward backwards in tests, meaning the code should not inspect the system's time directly.
