### ISSUE TITLE
Add direct decoder for Digest values

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#13]
Data can be validated before writing to the DB, when read, the data can be transmuted to the target value. Context: https://github.com/0xPolygonMiden/miden-node/pull/12#discussion_r1273939223

**Comment by hackaugusto** [comment]
@bobbinth what did you have in mind? Use `BaseElement::from_mont` instead of `BaseElement::new`?

**Comment by bobbinth** [comment]
For digests, I was thinking we'd store them as blobs - so, `RpoDigest::as_bytes()` should be fine.

When we store field elements individually (e.g., account ID), we probably want to use `BaseElement::new()` and its inverse `BaseElement::as_int()`. This way, the values are always in canonical form which would make inspecting the database via external tools simpler.

**Comment by bobbinth** [comment]
I guess the question is how do we instantiate `RpoDigest` when reading from the database - assuming we know that the underlying data is valid. Maybe we should implement `RpoDigest::from_bytes()` which would do this without checking the data?

**Comment by bobbinth** [comment]
@hackaugusto, @polydez - is this issue still relevant?

**Comment by polydez** [comment]
@bobbinth I don't think we should implement such backdoors for constructing `RpoDigest`. Even if we can assume that data in the database is under our control, there are still possibilities for data corruption, and for early bug detection it would be better to throw error on deserialization of such corrupted data instead of passing this data away and get error somewhere else. If this validation affects performance, it might be a reason to do so, but this function should be `unsafe`.

**Comment by bobbinth** [comment]
Closing is this issue as no longer relevant.
