### ISSUE TITLE
Notes not being inserted into the store

### ISSUE THREAD

**Issue by igamigo** [0xPolygonMiden/miden-node#147]
On `apply_block`, it seems incoming notes are not being correctly inserted in the store. After a quick inspection, I found a couple of issues with how the notes db works:

- First of all, inserts fail silently. I don't think this is desired especially on the debug binary.
- The `num_tag` constraint was incorrectly defined. PR for that: https://github.com/0xPolygonMiden/miden-node/pull/146
- After printing the errors on [`insert_notes`](https://github.com/0xPolygonMiden/miden-node/blob/758a0194efbeeb32b29f3d6a11f6c1a1ffa9930a/store/src/db/sql.rs#L267), I got this error: `out of range integral type conversion attempted`. I believe this is because `u64` is not supported by default on sqlite, and `tag` and `sender` are both inserted and retrieved as `u64` but they are stored as `i64` within the DB. I could be wrong but after a quick fix it seems that's the case

**Comment by bobbinth** [comment]
For the first one, we kind of already have an issue: https://github.com/0xPolygonMiden/miden-node/issues/115 - so, general error handling/reporting can be addressed as a part of this.

Since #146 has been merged, the only thing remaining is to fix the out-of-range error. @hackaugusto or @igamigo - could one of you make a PR for this?

**Comment by hackaugusto** [comment]
@igamigo I'm not going to pick this up today, so feel free to implement the PR. To me the hypothesis makes sense, and it is definitely a bug.

IMO the fix should be to add a wrapping struct and implement automatic converters, since this seem to be an issue happening on multiple places. Unfortunately the `Felt` type is defined in the crypto crate, so we can't implement `ToSql` and `FromSql` for it, so we need a wrapper type here.

**Comment by igamigo** [comment]
I created #148 as a possible fix. It is just a draft in order to unblock me for now, will focus on getting it merged after everything else looks ok (between the client and node)

**Comment by igamigo** [comment]
Found also that the sync state request tries to match notes both by sender and tag at the same time, instead of being one or another (which I understand we want). Fixed in the above PR as well.

**Comment by bobbinth** [comment]
@igamigo this has been fixed by #156, right? If so, let's close this issue.

**Comment by igamigo** [comment]
Closing as this was indeed fixed by #156
