### ISSUE TITLE
Remove `block_path` from `SyncStateResponse`

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#164]
This would make `sync-state` endpoint more efficient and will improve handling of responses on the client. See https://github.com/0xPolygonMiden/miden-node/issues/152#issuecomment-1898116360 for more info.

**Comment by igamigo** [comment]
I think, in order to keep the `sync_state` protocol consistent, that we would need to construct the `MmrDelta` slightly different, as explained in this comment: https://github.com/0xPolygonMiden/miden-node/issues/152#issuecomment-1898116360 (unless this was planned for a future change or there si anything I'm missing)
