### ISSUE TITLE
Endpoint to persist a new block: `apply_block`

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#19]
Once the block producer creates a proof for a block batch, the proof should be saved into the store.

```[tasklist]
### Tasks
- [ ] Define the message corresponding to the block data [ref](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/block/header.rs)
- [ ] Add an endpoint and the request/response messages, it should receive and persist the data
```

**Comment by bobbinth** [comment]
I usually refer to this endpoint as `apply_block`, and this would probably be the only endpoint through which we would write data into the store.

**Comment by bobbinth** [comment]
A few thoughts about how locking could work in the context of `apply_block`:

When `apply_block` is executing we want to achieve the following:
1. `apply_block` is atomic - i.e., either the whole block is applies or none of it (i.e., a crash in the middle of `apply_block` does not corrupt the database).
2. While `apply_block` is executing, any read requests to the store should return the data at the state prior to when the `apply_block` started executing.
3. Ideally, executing `apply_block` should not block any reads, but we can accept a short blocking duration (e.g., no more than 5 ms).

To achieve the first two of the above goals we need to apply changes to the database in a single transaction. But since we also have in-memory data (i.e., account and nullifier trees and chain MMR), we need to update them in a consistent manner as well.

Here is one option how to do this:
1. First, as we start executing `apply_block` we start a write transaction in the database.
2. We write the all the updates to the database.
  a. While this happening, assuming we use WAL mode, no reads on the store are blocked.
3. After all data has been written to the DB, we acquire a write lock on the in-memory structures.
  a. This will block all the reads.
4. Once the read lock on the in-memory structures has been acquired, we commit the transaction to the database.
5. We update in-memory structures.
6. Once all updates have been applied, we release the lock on in-memory structures.
  a. After this, all reads are un-blocked.

To avoid deadlocks and ensure consistency of data, we need to make sure that whenever we fulfill a read request to the store, we first acquire a read lock on in-memory structures, and only then read from the database.

Here is how this achieves the stated goals:
- A crush before step 4 does not commit any changes to the database - so, we are good. A crush after step 4, will re-build in-memory structures from the data in the database.
- During steps 1 - 3, the clients do not see the data being written into the database and the in-memory structures have not yet been updated - so, the clients receive consistent view of the data. During steps 4 - 6, the client's read requests are blocked - so, they don't see any inconsistencies either.
- We block reads only during steps 4 - 6 - so, while the database is being updated, the read requests can be fulfilled. We do block read requests during steps 4 - 6, but this step should be relatively short even now, and in the future we can optimizes this to move most of the work (i.e., hashing) before we acquire the write locks on in-memory structures.
