### ISSUE TITLE
`BlockNumber::block_num` and `BlockNumber::version` should be `u64`

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#84]
They are [currently](https://github.com/0xPolygonMiden/miden-node/blob/998eff647b7c2a8fa3d034519e65ab1759ef4061/proto/proto/block_header.proto#L10) `u32`; however, on-chain they are represented by `Felt`, so shouldn't they be `u64`?

I started making the change, but then this is baked into our `sqlite` code, and so is a more involved change. Is there some limitation from `sqlite` that prevents us from using `u64`?

**Comment by igamigo** [comment]
I believe [sqlite does not support `u64`](https://stackoverflow.com/questions/8496730/binding-an-unsigned-long-uint64-in-an-sqlite3-statement-c). Any similar type (eg `UNSIGNED BIG INT`) has an affinity of `INTEGER` (`i64`). You can however interpret your `u64` as `i64` in Rust code when executing a sqlite transaction (and `i64` as `u64` when reading results from transactions) without data loss/corruption: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a180f72b629dddfd5cc0cabe2b81699b

**Comment by plafer** [comment]
Thank you for the insight! So given what you've just shown, this confirms that we should indeed be able to represent `BlockNumber::block_num` and `BlockNumber::version` as `u64` - we store it as `UNSIGNED BIG INT` in sqlite, retrieve in Rust's sqlite library as `i64` (I assume), and type cast to `u64`.

**Comment by bobbinth** [comment]
At the protocol level, I'd still keep it as `u32` (assuming 3-second block times, this actually gives us 400+ years). How we store this in the database could be different (e.g., storing it as `i64` may be fine if it simplifies things).

> protobuf uses varint encoding for the field and the mismatch forces us to do a lot of conversions here and there

Why does this happen? I would have imagined that we get a `u32` from protobuf deserializer and then no other conversions are necessary.

**Comment by hackaugusto** [comment]
> At the protocol level, I'd still keep it as u32

Again, this has no benefit:

```rust
use prost::Message;

#[derive(Clone, PartialEq, Message)]
struct A {
    #[prost(uint32, tag = "1")]
    a: u32,
}

#[derive(Clone, PartialEq, Message)]
struct B {
    #[prost(uint64, tag = "1")]
    a: u64,
}

fn main() {
    println!("Value 0");
    println!("A: {:?}", A { a: 0 }.encode_to_vec());
    println!("B: {:?}", B { a: 0 }.encode_to_vec());

    println!("Value 256");
    println!("A: {:?}", A { a: 256 }.encode_to_vec());
    println!("B: {:?}", B { a: 256 }.encode_to_vec());

    println!("Value 65536");
    println!("A: {:?}", A { a: 65536 }.encode_to_vec());
    println!("B: {:?}", B { a: 65536 }.encode_to_vec());
}
```

outputs:

```
Value 0
A: []
B: []
Value 256
A: [8, 128, 2]
B: [8, 128, 2]
Value 65536
A: [8, 128, 128, 4]
B: [8, 128, 128, 4]
```

The type just defines the upper limit and the encoding depends on the value being encoded. This decision only leads to discussion and has zero differences in the wire.

> Why does this happen? I would have imagined that we get a u32 from protobuf deserializer and then no other conversions are necessary.

Because we have to:

1. decode from bytes to the message
2. the message has a u32 in memory
3. anything that uses the block_num with a u64 / Felt needs conversion. [example](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/block/header.rs#L24)

**Comment by bobbinth** [comment]
Agreed that there are no benefits in terms of encoding efficiency - but I'd say that specifying an upper bound is still useful for a variety of reasons.

Also, in this case specifically, we should probably be using `fixed32` data type as we'll get to needing 4 bytes of variable encoding within about a month (assuming 3-second block times).

I went through the other protobuf definitions, and I think we should make the following changes:
- In the [BlockHeader](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/block_header.proto#L6) message
  - Change `block_num` type to `fixed32`.
  - I'm also wondering if we should change `timestamp` to `fixed32` as well because in our case variable-length encoding will always take 5 bytes. But I maybe saving one byte is not worth it.
- In the [Note](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/note.proto), [NoteCreated](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/requests.proto#L13), and [NoteSyncRecord](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/responses.proto#L34) messages:
  - Change `block_num` type to `fixed32`.
  - Change `sender` type to `AccountId`.
  - Change `tag` type to `fixed64` as in most cases this will be set to account ID.
  - Ideally, `num_assets` would be a `fixed8` (because it would always be a single byte), but there is no such type in protobuf.
- In the [GetBlockHeaderByNumberRequest](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/requests.proto#L32), [AccountHashUpdate](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/responses.proto#L23), [NullifierUpdate](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/responses.proto#L29), [NullifierTransactionInputRecord](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/responses.proto#L29), [SyncStateRequest](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/requests.proto#L40), and [NullifierLeaf](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/tsmt.proto#L23) messages:
  -  Change `block_num` type to `fixed32`.
- In the [SyncStateResponse](https://github.com/0xPolygonMiden/miden-node/blob/main/proto/proto/responses.proto#L43) message:
  - Change `chain_tip` to `fixed32`.

> anything that uses the block_num with a u64 / Felt needs conversion. example [1](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/block/header.rs#L24) [2](https://github.com/0xPolygonMiden/miden-node/blob/main/store/src/state.rs#L413-L416).

I would say that in the first example, we should probably change `block_num` (as well as `timestamp` and `version`) to non-`Felt` data types.

In the second example, I think the conversion cannot be avoided as we are converting from `Word` to either `u64` or `u32`.

**Comment by plafer** [comment]
Should we create a separate issue for this, and close this one?

**Comment by bobbinth** [comment]
> Should we create a separate issue for this, and close this one?

Yes, let's do it.

**Comment by plafer** [comment]
#112
